Add bookings
RakhmaIs/java-shareit pull request #5
Opened 2023-07-18 12:17 UTC by RakhmaIs

2023-07-19 07:09 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний!

Желаю удачи!

2023-07-19 07:09 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/dto/BookingRequestDto.java
> +    LocalDateTime end;
А почему здесь модификаторы доступа не повесил?

2023-07-19 07:09 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/dto/BookingRequestDto.java
> +@Setter
Раз `Data` стал использовать, то давай везде где это возможно добавим, чтобы 

1. уменьшить число аннотаций (одна вместо 2-3)
2. добиться единообразия в оформлении `dto`

2023-07-19 07:09 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                .orElseThrow(() -> new UserNotFoundException("Пользователь не найден"));
У тебя же есть для этой проверки `existsById` метод

2023-07-19 07:09 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        userRepository.findById(userId)
есть `existsById`

2023-07-19 07:09 UTC, LexLippi commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS users, items, bookings, comments CASCADE;
По возможности эту часть надо удалять.

Ни один пользователь не будет использовать продакшен-приложение, где при каждом удалении стираются все его данные.

2023-07-19 07:09 UTC, LexLippi commented on src/main/resources/schema.sql
> +    owner_id         BIGINT REFERENCES users (id) ON DELETE CASCADE,
может быть `null`?

2023-07-19 07:09 UTC, LexLippi commented on src/main/resources/schema.sql
> +    booking_status VARCHAR(10)
Могут быть `null`?

2023-07-19 07:09 UTC, LexLippi commented on src/main/resources/schema.sql
> +    created TIMESTAMP WITHOUT TIME ZONE
1. Могут быть `null`?
2. лучше по возможности не называть переменные зарезервированными ключевыми словами, такими как `text`

2023-07-19 11:19 UTC, RakhmaIs commented on src/main/java/ru/practicum/shareit/booking/dto/BookingRequestDto.java
> +    LocalDateTime end;
Добавил модификаторы)

2023-07-19 11:21 UTC, RakhmaIs commented on src/main/java/ru/practicum/shareit/booking/dto/BookingRequestDto.java
> +@Setter
Где возможно оставил только Dаta и Builder

2023-07-19 11:22 UTC, RakhmaIs commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                .orElseThrow(() -> new UserNotFoundException("Пользователь не найден"));
Так же везде где не нужен объект изменил на метод existById

2023-07-19 11:22 UTC, RakhmaIs commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        userRepository.findById(userId)
Так же везде где не нужен объект изменил на метод existById

2023-07-19 11:22 UTC, RakhmaIs commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS users, items, bookings, comments CASCADE;
Удалил

2023-07-19 11:22 UTC, RakhmaIs commented on src/main/resources/schema.sql
> +    owner_id         BIGINT REFERENCES users (id) ON DELETE CASCADE,
Добавил NOT NULL

2023-07-19 11:23 UTC, RakhmaIs commented on src/main/resources/schema.sql
> +    booking_status VARCHAR(10)
Добавил NOT NULL

2023-07-19 11:23 UTC, RakhmaIs commented on src/main/resources/schema.sql
> +    created TIMESTAMP WITHOUT TIME ZONE
Добавил NOT NULL,  изменил text на text_comment

2023-07-20 09:22 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2023-07-20 11:31 UTC, merged