Technical task №16 - done
RakhmaIs/java-shareit pull request #7
Opened 2023-08-12 14:40 UTC by RakhmaIs

2023-08-13 21:04 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некотрое количество замечаний, которые надо исправить.

Желаю удачи!

2023-08-13 21:04 UTC, LexLippi commented on server/src/test/java/ru/practicum/shareit/user/controllertest/UserControllerTest.java
> +    }*/
Лучше удалять тесты, если в них нет необходимости

2023-08-13 21:04 UTC, LexLippi commented on server/src/test/java/ru/practicum/shareit/item/servicetest/ItemServiceImplTest.java
> +}*/
Аналогично про закомментированные классы, нет необходимости хранить их в программе

2023-08-13 21:04 UTC, LexLippi commented on server/src/test/java/ru/practicum/shareit/booking/controllertest/BookingControllerTest.java
> +    }*/
Уже писал про это.
Для того, чтобы легко было восстановить эти данные, мы пользуемся системой контроля версий.
Но хранить их не нужно

В соответствии с принципом KISS:
https://en.wikipedia.org/wiki/KISS_principle

2023-08-13 21:04 UTC, LexLippi commented on server/src/main/java/ru/practicum/shareit/util/Pagination.java
> +    }*/
Не надо это комментировать

2023-08-13 21:04 UTC, LexLippi commented on server/src/main/java/ru/practicum/shareit/util/Pagination.java
> +            return PageRequest.of(0, Integer.MAX_VALUE, sortCreated);
Не стоит использовать `MAX_VALUE`.
Это очень большой запрос в БД, стоит уменьшить ограничение, например до 20

2023-08-13 21:04 UTC, LexLippi commented on server/src/main/java/ru/practicum/shareit/item/ItemController.java
>                                                                    @RequestParam(name = "size", required = false) Integer size) {
Возможно проще использовать `defaultValue`

2023-08-13 21:04 UTC, LexLippi commented on server/src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                                  @RequestParam(name = "size", required = false/*, defaultValue = "10"*/)
Почему закомментировал?

2023-08-13 21:04 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/item/ItemClientController.java
> +                                                      defaultValue = "0") Integer from,
Нет необходимости в `required = false`, если используем `defaultValue`

2023-08-14 09:32 UTC, RakhmaIs commented on server/src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                                  @RequestParam(name = "size", required = false/*, defaultValue = "10"*/)
Очень торопился, и что-то не работало - проверял что, а расскоментить забыл)

2023-08-14 12:02 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи с дипломным проектом!

2023-08-14 12:58 UTC, RakhmaIs commented
> Привет!
> 
> Хорошая работа!
> 
> Желаю удачи с дипломным проектом!

Привет, спасибо большое :)

2023-08-14 12:58 UTC, merged